function modelId(model: string) { return model.toLowerCase().replace(/^antigravity-/, "").replace(/-(low|medium|high)$/i, ""); }
function contentParts(content: any) { if (Array.isArray(content)) return content.flatMap((p) => p.type === "text" ? [{ text: p.text }] : []); return [{ text: String(content ?? "") }]; }
export function toGoogleBody(body: any, projectId: string, sessionId = crypto.randomUUID()) {
  const system = body.messages?.find((m: any) => m.role === "system");
  const contents = (body.messages ?? []).filter((m: any) => m.role !== "system").map((m: any) => ({ role: m.role === "assistant" ? "model" : "user", parts: contentParts(m.content) }));
  const request: any = { contents, generationConfig: { temperature: body.temperature ?? 0.7, maxOutputTokens: body.max_tokens ?? 4096, topP: body.top_p ?? 0.95 }, sessionId };
  if (system) request.systemInstruction = { parts: contentParts(system.content) };
  if (body.tools?.length) request.tools = [{ functionDeclarations: body.tools.map((tool: any) => ({ name: tool.function.name.replace(/[^a-zA-Z0-9_]/g, "_"), description: tool.function.description ?? "", parameters: tool.function.parameters ?? { type: "object", properties: {} } })) }];
  return { project: projectId, model: modelId(body.model), userAgent: "antigravity", requestId: `agent-${crypto.randomUUID()}`, requestType: "agent", request };
}
export function googleEventToOpenAI(data: any, model: string, id: string) {
  const value = data.response ?? data; const candidate = value.candidates?.[0]; const parts = candidate?.content?.parts ?? []; const delta: any = {};
  for (const part of parts) { if (part.text) delta[part.thought ? "reasoning_content" : "content"] = `${delta[part.thought ? "reasoning_content" : "content"] ?? ""}${part.text}`; if (part.functionCall) delta.tool_calls = [{ index: 0, id: part.functionCall.id ?? `call_${crypto.randomUUID()}`, type: "function", function: { name: part.functionCall.name, arguments: JSON.stringify(part.functionCall.args ?? {}) } }]; }
  const reason = candidate?.finishReason; const finish_reason = reason === "STOP" ? "stop" : reason === "MAX_TOKENS" ? "length" : reason ? "stop" : null;
  const usageMetadata = value.usageMetadata; return { id, object: "chat.completion.chunk", created: Math.floor(Date.now() / 1000), model, choices: [{ index: 0, delta, finish_reason }], ...(usageMetadata ? { usage: { prompt_tokens: usageMetadata.promptTokenCount ?? 0, completion_tokens: usageMetadata.candidatesTokenCount ?? 0, total_tokens: usageMetadata.totalTokenCount ?? 0 } } : {}) };
}
export function googleStreamToOpenAI(response: Response, model: string, id: string) { const reader = response.body?.getReader(); if (!reader) throw new Error("Antigravity returned an empty stream"); const decoder = new TextDecoder(); const encoder = new TextEncoder(); let buffer = ""; return new Response(new ReadableStream({ async start(controller) { const emit = (data: any) => controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`)); try { while (true) { const { done, value } = await reader.read(); buffer += decoder.decode(value ?? new Uint8Array(), { stream: !done }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { const raw = line.trim().replace(/^data:\s*/, ""); if (!raw || raw === "[DONE]") continue; try { const event = googleEventToOpenAI(JSON.parse(raw), model, id); if (event.choices[0].delta.content || event.choices[0].delta.reasoning_content || event.choices[0].delta.tool_calls || event.choices[0].finish_reason) emit(event); } catch {} } if (done) break; } emit({ id, object: "chat.completion.chunk", created: Math.floor(Date.now() / 1000), model, choices: [{ index: 0, delta: {}, finish_reason: "stop" }] }); controller.enqueue(encoder.encode("data: [DONE]\n\n")); } catch (error: any) { emit({ error: { message: error.message } }); } finally { controller.close(); } } }), { headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" } }); }
