import { useState } from "react";
import { RiCheckLine as Check, RiLoader4Line as LoaderCircle, RiMoonLine as MoonLine, RiSunLine as SunLine } from "@remixicon/react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { settings } from "../api/client";

export default function SettingsPage({ darkMode, onThemeChange }: { darkMode: boolean; onThemeChange: (value: boolean) => void }) {
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const submit = async () => { setError(null); setSuccess(null); if (!current) return setError("Current password is required."); if (next.length < 4) return setError("New password must be at least 4 characters."); if (next !== confirm) return setError("Passwords do not match."); setSaving(true); try { const result = await settings.changePassword(current, next); setSuccess(result.message); setCurrent(""); setNext(""); setConfirm(""); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  return <div className="w-full space-y-6 p-6"><h1 className="font-heading text-2xl font-semibold tracking-tight">Settings</h1><Card><CardHeader><CardTitle>Appearance</CardTitle></CardHeader><CardContent><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-md bg-muted">{darkMode ? <MoonLine className="size-4" /> : <SunLine className="size-4" />}</div><div><div className="text-sm font-medium">Dark mode</div><div className="text-xs text-muted-foreground">{darkMode ? "Dark theme is enabled" : "Light theme is enabled"}</div></div></div><Switch checked={darkMode} onCheckedChange={onThemeChange} aria-label="Toggle dark mode" /></div></CardContent></Card><Card><CardHeader><CardTitle>Change panel password</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><div className="space-y-2"><Label htmlFor="current-password">Current password</Label><Input id="current-password" type="password" value={current} onChange={(e) => setCurrent(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="new-password">New password</Label><Input id="new-password" type="password" value={next} onChange={(e) => setNext(e.target.value)} /><p className="text-xs text-muted-foreground">Minimum 4 characters.</p></div><div className="space-y-2"><Label htmlFor="confirm-password">Confirm password</Label><Input id="confirm-password" type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} /></div></div>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{success && <Alert variant="default"><Check className="size-4" /><AlertDescription>{success}</AlertDescription></Alert>}<Button onClick={submit} disabled={saving}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : null}{saving ? "Saving..." : "Change password"}</Button></CardContent></Card></div>;
}
